### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by jfayre** [Sowintuu/voiceAtis#1]
Hi,
It looks like pyuipc is now compatible with python 3 as of the latest FSUIPC sdk release notes. Do you plan to port this application to Python 3?

**Comment by Sowintuu** [comment]
Hi,
That is great news as I'm trying to avoid Python 2 where I can. Thanks for the information!
As I currently have no time to work on the application, do not expect a port soon. But when I continue with my work, I will definitely port it to Python 3.

**Comment by Sowintuu** [comment]
The application was ported to Python 3.8 with v0.2.0. Thank you again for the hint!
