### ISSUE TITLE
Feature Request: Flightgear support

### ISSUE THREAD

**Issue by vezza** [Sowintuu/voiceAtis#3]
It would be nice if this project could be extended to support Flightgear flight sim

**Comment by Sowintuu** [comment]
This plugin is based on FSUIPC. In fact, Flightgear is already supported, as there is a (early) version of this interface for flightgear too. If all necessary Offsets are supported, it should work. See here: https://github.com/geneb/win-fguipc
However, I'm not sure if it will bring a good value to this flight simulator as I'm not aware if you can fly on the IVAO network.
